import KakaoTripMap from "@/components/KakaoTripMap";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Images, MapPin, Printer, Repeat2, Route, StickyNote } from "lucide-react";
import { useRoute } from "wouter";

export default function SharedTrip() {
  const [, params] = useRoute("/share/:token");
  const trip = trpc.trip.shared.useQuery({ token: params?.token ?? "" }, { enabled: Boolean(params?.token) });

  if (trip.isLoading) return <div className="grid min-h-screen place-items-center bg-[#f5f1e8] font-display text-3xl">여정을 불러오는 중</div>;
  if (!trip.data) return <div className="grid min-h-screen place-items-center bg-[#f5f1e8] p-6 text-center"><div><p className="font-display text-5xl">공유 링크를 찾지 못했습니다.</p><p className="mt-4 text-sm text-stone-500">링크가 만료되었거나 삭제된 계획입니다.</p></div></div>;

  const destinations = trip.data.stops.map(stop => ({ id: String(stop.id), name: stop.name, address: stop.address, latitude: Number(stop.latitude), longitude: Number(stop.longitude), note: stop.note ?? "", photos: stop.photos?.map(photo => ({ storageKey: photo.storageKey, url: photo.url, fileName: photo.fileName, takenAt: photo.takenAt ? new Date(String(photo.takenAt)).toISOString().slice(0, 10) : undefined, description: photo.description ?? undefined })) ?? [] }));
  const fixedStart = trip.data.fixedStartName && trip.data.fixedStartAddress && trip.data.fixedStartLatitude !== null && trip.data.fixedStartLongitude !== null ? { id: `shared-start-${trip.data.id}`, name: trip.data.fixedStartName, address: trip.data.fixedStartAddress, latitude: Number(trip.data.fixedStartLatitude), longitude: Number(trip.data.fixedStartLongitude) } : null;
  return <main className="min-h-screen bg-[#f5f1e8] p-5 sm:p-10"><div className="mx-auto max-w-6xl"><p className="text-[10px] font-bold uppercase tracking-[0.24em] text-[#c4503d]">Shared municipal itinerary</p><div className="mt-4 flex flex-col justify-between gap-5 border-b border-black/15 pb-7 sm:flex-row sm:items-end"><div><h1 className="font-display text-5xl leading-none sm:text-7xl">{trip.data.title}</h1><p className="mt-4 text-sm text-stone-600">{String(trip.data.tripDate)} · 담당 {trip.data.managerName}</p></div><Button onClick={() => window.print()} variant="outline" className="print:hidden rounded-none border-black/20 bg-transparent"><Printer className="mr-2 h-4 w-4" /> 인쇄</Button></div><div className="mt-7 grid gap-7 lg:grid-cols-[1fr_300px]"><div className="h-[520px] overflow-hidden border border-black/15"><KakaoTripMap destinations={destinations} fixedStart={fixedStart} returnToStart={Boolean(trip.data.returnToStart)} onMapClick={() => undefined} /></div><aside><div className="route-card"><Route className="h-5 w-5 text-[#c4503d]" /><p className="mt-8 text-[10px] font-bold uppercase tracking-[0.2em] text-stone-500">{trip.data.returnToStart ? "왕복 경로 요약" : "경로 요약"}</p><p className="font-display mt-2 text-4xl">{Number(trip.data.routeDistanceKm).toFixed(1)}km</p><p className="mt-2 text-sm text-stone-600">예상 {trip.data.routeDurationMinutes}분</p></div>{fixedStart ? <div className="mt-4 border-l-2 border-[#c4503d] bg-[#eee9de] p-4"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#8a5a50]">{trip.data.returnToStart ? "고정 출발지 · 왕복 복귀" : "고정 출발지"}</p><p className="mt-2 text-sm font-semibold">{fixedStart.name}</p><p className="mt-1 text-xs text-stone-500">{fixedStart.address}</p></div> : null}<ol className="mt-5 border-t border-black/15 pt-4">{destinations.map((destination, index) => <li key={destination.id} className="flex gap-3 border-b border-black/10 py-3"><span className="font-display text-xl text-[#c4503d]">{String(index + 1).padStart(2, "0")}</span><div><p className="text-sm font-semibold">{destination.name}</p><p className="mt-1 text-xs text-stone-500">{destination.address}</p>{destination.note ? <p className="shared-stop-note"><StickyNote className="h-3 w-3" />{destination.note}</p> : null}{destination.photos?.length ? <div className="shared-photo-grid">{destination.photos.map(photo => <figure key={photo.storageKey}><img src={photo.url} alt={`${destination.name} 현장 사진`} />{photo.takenAt || photo.description ? <figcaption>{photo.takenAt ? `${photo.takenAt} · ` : ""}{photo.description ?? ""}</figcaption> : null}</figure>)}</div> : null}</div></li>)}{trip.data.returnToStart && fixedStart ? <li className="route-return-leg"><Repeat2 className="h-3.5 w-3.5" /> {fixedStart.name} 복귀</li> : null}</ol></aside></div></div></main>;
}
